<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">memoryHog</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ci8vIGdldCBpbnB1dCBvbiBob3cgbWFueSBvYmplY3RzIChhcnJheSBzaXplKSBhbmQgaG93IGxh
cmdlIGFuIG9iamVjdCAobWVtb3J5cGVyT2JqZWN0KSBmcm9tIAovLyB0aGUgcGlwZWxpbmUKCgoJ
SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsKCUludGVn
ZXIgbWVtb3J5SW50ZWdlciA9IG5ldyBJbnRlZ2VyKCAgSURhdGFVdGlsLmdldFN0cmluZyggcGlw
ZWxpbmVDdXJzb3IsICJtZW1vcnlUb0dyYWJQZXJPYmplY3QiICkgICk7CglJbnRlZ2VyIGFycmF5
U2l6ZUludGVnZXIgPSBuZXcgSW50ZWdlciggIElEYXRhVXRpbC5nZXRTdHJpbmcoIHBpcGVsaW5l
Q3Vyc29yLCAib2JqZWN0QXJyYXlTaXplIiApICApOwogCi8vIGluc3RhbnRpYXRlIHRoaXMgYXJi
aXRyYXJpbHkgc2l6ZWQgb2JqZWN0CgoJaW50IGFycmF5U2l6ZSA9IGFycmF5U2l6ZUludGVnZXIu
aW50VmFsdWUoKTsKCU9iamVjdFtdIG1lbW9yeUhvbGRlciA9IG5ldyBPYmplY3RbYXJyYXlTaXpl
XTsKCWludCBjb3VudCA9IDA7Cglmb3IgKDsgY291bnQgPCBhcnJheVNpemU7IGNvdW50KyspCgl7
CgkgIG1lbW9yeUhvbGRlcltjb3VudF0gPSBuZXcgYnl0ZVttZW1vcnlJbnRlZ2VyLmludFZhbHVl
KCldOwoJfQoKLy9ub3cgY29weSB0aGlzIG9iamVjdAoKCU9iamVjdFtdIGNvcHlPZk1lbUhvbGRl
ciA9IG5ldyBPYmplY3RbYXJyYXlTaXplXTsKCWNvdW50ID0gMDsKCWZvciAoOyBjb3VudCA8IGFy
cmF5U2l6ZTsgY291bnQrKykKCXsKCSAgY29weU9mTWVtSG9sZGVyW2NvdW50XSA9IG1lbW9yeUhv
bGRlcltjb3VudF07Cgl9CgpwaXBlbGluZUN1cnNvci5kZXN0cm95KCk7Cgo=</value>
</Values>
