<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">writeToFile</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ci8vIGdldCBwaXBlbGluZSBkYXRhCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxp
bmUuZ2V0Q3Vyc29yICgpOwpwaXBlbGluZUN1cnNvci5maXJzdCAoImlucHV0U3RyaW5nIik7ClN0
cmluZyBpbnB1dFN0cmluZyA9IChTdHJpbmcpIHBpcGVsaW5lQ3Vyc29yLmdldFZhbHVlICgpOwpw
aXBlbGluZUN1cnNvci5kZXN0cm95ICgpOwoJCnRyeQp7CiAgIERhdGUgdG9kYXkgPSBuZXcgRGF0
ZSAoKTsKICAgU2ltcGxlRGF0ZUZvcm1hdCBmb3JtYXR0ZXIgPSBuZXcgU2ltcGxlRGF0ZUZvcm1h
dCAoIk1NLWRkLXl5eXkiKTsKICAgU3RyaW5nIHJlZ0ZpbGVOYW1lID0gIkVycm9yRmlsZV8iICsg
Zm9ybWF0dGVyLmZvcm1hdCAodG9kYXkpICsgIi50eHQiOwoJCQogICBTdHJpbmdCdWZmZXIgc3Ry
QnVmZmVyID0gbmV3IFN0cmluZ0J1ZmZlciAoKTsKCQkKICAgc3RyQnVmZmVyLmFwcGVuZCAoaW5w
dXRTdHJpbmcgKyAiXG4iKTsKCQkKICAgYnl0ZSBbXSBidWZXcml0ZSA9IHN0ckJ1ZmZlci50b1N0
cmluZyAoKS5nZXRCeXRlcyAoKTsKCQkKICAgRmlsZU91dHB1dFN0cmVhbSByZWdXcml0ZSA9IG5l
dyBGaWxlT3V0cHV0U3RyZWFtIChyZWdGaWxlTmFtZSwgdHJ1ZSk7CiAgIHJlZ1dyaXRlLndyaXRl
IChidWZXcml0ZSk7CiAgIHJlZ1dyaXRlLmNsb3NlICgpOwoJCQkJCQp9CgpjYXRjaCAoSU9FeGNl
cHRpb24gaWUpIAp7CiAgIGllLnByaW50U3RhY2tUcmFjZSAoKTsKfQpjYXRjaCAoRXhjZXB0aW9u
IGUpIAp7CiAgIGUucHJpbnRTdGFja1RyYWNlICgpOwp9Cgo=</value>
</Values>
