<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">calculateFactorial</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gVGhpcyBzZXJ2aWNlIGNhbGN1bGF0ZXMgYSBmYWN0b3JpYWwgcmVzdWx0DQovLyBJbiBtYXRo
ZW1hdGljcywgdGhlIGZhY3RvcmlhbCBvZiBhIG5vbi1uZWdhdGl2ZSBpbnRlZ2VyIG4sIGRlbm90
ZWQgYnkgbiEsIGlzIHRoZSBwcm9kdWN0IG9mIGFsbCBwb3NpdGl2ZSBpbnRlZ2VycyBsZXNzIHRo
YW4gb3IgZXF1YWwgdG8gbi4gDQovLyBGb3IgZXhhbXBsZSwNCi8vIAkJNSEgPSA1ICBcdGltZXMg
IDQgIFx0aW1lcyAgMyAgXHRpbWVzICAyICBcdGltZXMgIDEgPSAxMjAuICBcIA0KLy8gcGlwZWxp
bmUNCg0KSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsN
ClN0cmluZwlpbiA9IElEYXRhVXRpbC5nZXRTdHJpbmcoIHBpcGVsaW5lQ3Vyc29yLCAiZmFjdG9y
aWFsSW5wdXQiICk7DQpwaXBlbGluZUN1cnNvci5kZXN0cm95KCk7DQoNCmludCBuaW4gPSBJbnRl
Z2VyLnBhcnNlSW50KGluKTsNCkJpZ0ludGVnZXIgZmFrID0gQmlnSW50ZWdlci5PTkU7DQpmb3Ig
KGludCBrID0gMjsgayA8PSBuaW47IGsrKykgew0KCWZhayA9IGZhay5tdWx0aXBseShuZXcgQmln
SW50ZWdlcihJbnRlZ2VyLnRvU3RyaW5nKGspKSk7DQp9DQoNCmNhbGxzKys7DQoNCi8vIHBpcGVs
aW5lDQpJRGF0YUN1cnNvciBwaXBlbGluZUN1cnNvcl8xID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7
DQpJRGF0YVV0aWwucHV0KCBwaXBlbGluZUN1cnNvcl8xLCAiZmFjdG9yaWFsUmVzdWx0IiwgZmFr
LnRvU3RyaW5nKCkgKTsNCnBpcGVsaW5lQ3Vyc29yXzEuZGVzdHJveSgpOw0KCQ==</value>
</Values>
