<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">doGlobalSearch</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGEgaWRhdGFGaWxsID0gSURhdGFGYWN0b3J5LmNyZWF0ZSgpOw0KSURhdGFNYXAgZmlsbE1h
cCA9IG5ldyBJRGF0YU1hcChpZGF0YUZpbGwpOw0KZmlsbE1hcC5wdXQoImNhY2hlTWFuYWdlck5h
bWUiLCAiVGVzdENhY2hlTWFuYWdlciIpOw0KZmlsbE1hcC5wdXQoImNhY2hlTmFtZSIsICJDdXN0
b21lckNhY2hlIik7DQpmaWxsTWFwLnB1dCgiaW5jbHVkZUtleSIsICJ0cnVlIik7DQpmaWxsTWFw
LnB1dCgiaW5jbHVkZVZhbHVlIiwgInRydWUiKTsNCmZpbGxNYXAucHV0KCJjcml0ZXJpYSIsIElE
YXRhRmFjdG9yeS5jcmVhdGUoKSk7DQp0cnkgew0KCUlEYXRhIHJlc3VsdCA9IFNlcnZpY2UuZG9J
bnZva2UoTlNOYW1lLmNyZWF0ZSgicHViLmNhY2hlOnNlYXJjaCIpLCBpZGF0YUZpbGwpOw0KCU9i
amVjdFtdIG9iamVjdCA9IChPYmplY3RbXSkgSURhdGFVdGlsLmdldChyZXN1bHQuZ2V0Q3Vyc29y
KCksICJyZXN1bHQiKTsNCgkNCglTeXN0ZW0ub3V0LnByaW50bG4oIi8vLyoqKioqKioqKioqKioq
KioqKipSRVNVTFQqKioqKioqKioqKioqKioqKioqKioqKioqKioqKi8vLyIpOw0KCWZvciAoaW50
IGkgPSAwOyBpIDwgb2JqZWN0Lmxlbmd0aDsgaSsrKSB7DQoJCVBlcnNvbiB2YWx1ZSA9IChQZXJz
b24pICgoU2VhcmNoUmVzdWx0KSBvYmplY3RbaV0pLmdldFZhbHVlKCk7DQoJCVN5c3RlbS5vdXQu
cHJpbnRsbih2YWx1ZSk7DQoJfQ0KCVN5c3RlbS5vdXQucHJpbnRsbigiLy8vKioqKioqKioqKioq
KioqKioqKlJFU1VMVCoqKioqKioqKioqKioqKioqKioqKioqKioqKioqLy8vIik7DQp9IGNhdGNo
IChFeGNlcHRpb24gZSkgew0KCWUucHJpbnRTdGFja1RyYWNlKCk7DQp9</value>
</Values>
